"""Thin wrapper around ``requests`` for fetching GitHub release assets.

Covers two usage shapes:
  - ``download_asset(repo, tag, name, dest)`` pulls a single asset by file
    name into ``dest`` and returns the path.
  - ``download_tarball(repo, tag, dest)`` fetches the source-code tarball
    GitHub generates automatically (the ``.tar.gz`` attached to every
    release, distinct from release assets).

Both forms verify a sha256 if one is provided, cache under
``<project_root>/.cache/<repo>/<tag>/`` so repeated CI runs don't
re-download, and respect ``GITHUB_TOKEN`` / ``GH_TOKEN`` when set so
private repos (and authenticated rate limits) work without extra
wiring.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import requests

from ..config import REPO_ROOT


GITHUB_API = "https://api.github.com"
CACHE_ROOT = REPO_ROOT / ".cache" / "artifacts"
_CHUNK = 1 << 16


def _auth_headers() -> dict[str, str]:
    """Use a token if one is available to avoid the 60-req/h anonymous cap."""
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _cache_dir(repo: str, tag: str) -> Path:
    out = CACHE_ROOT / repo / tag
    out.mkdir(parents=True, exist_ok=True)
    return out


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while chunk := f.read(_CHUNK):
            h.update(chunk)
    return h.hexdigest()


def _stream_download(url: str, dest: Path, *, headers: dict[str, str]) -> None:
    tmp = dest.with_suffix(dest.suffix + ".part")
    with requests.get(url, headers=headers, stream=True, timeout=60) as resp:
        resp.raise_for_status()
        with tmp.open("wb") as f:
            for chunk in resp.iter_content(chunk_size=_CHUNK):
                if chunk:
                    f.write(chunk)
    tmp.rename(dest)


def download_asset(
    repo: str,
    tag: str,
    name: str,
    *,
    expected_sha256: str | None = None,
) -> Path:
    """Download ``name`` from the release tagged ``tag`` of ``repo``."""
    cache = _cache_dir(repo, tag)
    dest = cache / name
    if dest.exists() and (expected_sha256 is None or _sha256_file(dest) == expected_sha256):
        return dest

    # Resolve the release, then find the matching asset by name. Going
    # through the API (rather than a hard-coded download URL) lets us
    # surface useful errors when the tag or asset doesn't exist.
    api_url = f"{GITHUB_API}/repos/{repo}/releases/tags/{tag}"
    resp = requests.get(api_url, headers=_auth_headers(), timeout=30)
    resp.raise_for_status()
    release = resp.json()
    assets = release.get("assets") or []
    match = next((a for a in assets if a["name"] == name), None)
    if match is None:
        have = ", ".join(a["name"] for a in assets) or "<none>"
        raise FileNotFoundError(f"asset '{name}' not on {repo}@{tag}. available: {have}")

    _stream_download(match["browser_download_url"], dest, headers=_auth_headers())

    if expected_sha256 is not None:
        got = _sha256_file(dest)
        if got != expected_sha256:
            dest.unlink(missing_ok=True)
            raise ValueError(
                f"{repo}@{tag}/{name}: sha256 mismatch (got {got}, expected {expected_sha256})"
            )

    return dest


def download_source_tarball(repo: str, tag: str) -> Path:
    """Fetch the release's own uploaded source tarball.

    Our releases attach a repo-name tarball (e.g. ``lorcana-schemas-0.4.0.tar.gz``)
    rather than relying on GitHub's autogenerated ``.tar.gz``. This helper is
    a thin convenience over :func:`download_asset` that infers the common
    ``<repo>-<version>.tar.gz`` naming.
    """
    # `v0.4.0` → `0.4.0`; `tournaments-v1.0.0` → `1.0.0`; any leading
    # word prefix ending in `-v` gets stripped.
    version = tag.split("-v")[-1].lstrip("v")
    repo_name = repo.split("/")[-1]
    name = f"{repo_name}-{version}.tar.gz"
    return download_asset(repo, tag, name)
